/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "MidiToImgVid"
include(":MidiToImgVid-lib")
include(":MidiToImgVid-cli")
project(":MidiToImgVid-lib").projectDir = file("lib")
project(":MidiToImgVid-cli").projectDir = file("cli")
